2022-02-11 06:19:04,948 ERROR: Exception on /user/jake [GET] [in /home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/jake/ShotStar/app/main/routes.py", line 59, in user
    return render_template('user.html', user=user, games=games.items, next_url=next_url, prev_url=prev_url, form=form)
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jake/ShotStar/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jake/ShotStar/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/jake/ShotStar/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/jake/ShotStar/app/templates/user.html", line 10, in block 'app_content'
    {% if user.last_seen %}<p>Last seen on: {{ moment(user.last_seen).format('LLL') }}</p>{% endif %}
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'moment' is undefined
2022-02-11 06:20:49,229 INFO: ShotStar startup [in /home/jake/ShotStar/app/__init__.py:70]
2022-02-11 06:20:52,833 ERROR: Exception on /user/jake [GET] [in /home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/jake/ShotStar/app/main/routes.py", line 59, in user
    return render_template('user.html', user=user, games=games.items, next_url=next_url, prev_url=prev_url, form=form)
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jake/ShotStar/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jake/ShotStar/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/jake/ShotStar/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/jake/ShotStar/app/templates/user.html", line 10, in block 'app_content'
    {% if user.last_seen %}<p>Last seen on: {{ moment(user.last_seen).format('LLL') }}</p>{% endif %}
  File "/home/jake/ShotStar/venv/lib/python3.8/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'moment' is undefined
2022-02-11 06:21:32,585 INFO: ShotStar startup [in /home/jake/ShotStar/app/__init__.py:71]
2022-02-11 06:27:49,710 INFO: ShotStar startup [in /home/jake/ShotStar/app/__init__.py:71]
2022-02-11 06:28:02,315 INFO: ShotStar startup [in /home/jake/ShotStar/app/__init__.py:71]
2022-02-11 06:28:08,082 INFO: ShotStar startup [in /home/jake/ShotStar/app/__init__.py:71]
2022-02-11 06:28:12,044 INFO: ShotStar startup [in /home/jake/ShotStar/app/__init__.py:71]
2022-02-11 06:29:40,415 INFO: ShotStar startup [in /home/jake/ShotStar/app/__init__.py:71]
2022-02-11 06:29:46,551 INFO: ShotStar startup [in /home/jake/ShotStar/app/__init__.py:71]
2022-02-11 06:29:50,625 INFO: ShotStar startup [in /home/jake/ShotStar/app/__init__.py:71]
2022-02-11 06:29:55,732 INFO: ShotStar startup [in /home/jake/ShotStar/app/__init__.py:71]
2022-02-11 06:29:59,965 INFO: ShotStar startup [in /home/jake/ShotStar/app/__init__.py:71]
